const electronicsProducts = [
  {
    id: 1,
    name: "Smartphone XYZ",
    brand: "Brand A",
    price: 69999,
    discountPrice: 64999,
    image: "https://via.placeholder.com/300x300?text=Smartphone+XYZ",
  },
  {
    id: 2,
    name: "Laptop ABC",
    brand: "Brand B",
    price: 129999,
    discountPrice: 119999,
    image: "https://via.placeholder.com/300x300?text=Laptop+ABC",
  },
  {
    id: 3,
    name: "Wireless Headphones",
    brand: "Brand C",
    price: 19999,
    discountPrice: 17999,
    image: "https://via.placeholder.com/300x300?text=Wireless+Headphones",
  },
  {
    id: 4,
    name: "4K Smart TV",
    brand: "Brand D",
    price: 89999,
    discountPrice: 84999,
    image: "https://via.placeholder.com/300x300?text=4K+Smart+TV",
  },
  {
    id: 5,
    name: "Smartwatch",
    brand: "Brand E",
    price: 29999,
    discountPrice: 27999,
    image: "https://via.placeholder.com/300x300?text=Smartwatch",
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    brand: "Brand F",
    price: 14999,
    discountPrice: 13999,
    image: "https://via.placeholder.com/300x300?text=Bluetooth+Speaker",
  },
  {
    id: 7,
    name: "Gaming Monitor",
    brand: "Brand G",
    price: 39999,
    discountPrice: 37999,
    image: "https://via.placeholder.com/300x300?text=Gaming+Monitor",
  },
  {
    id: 8,
    name: "Action Camera",
    brand: "Brand H",
    price: 24999,
    discountPrice: 22999,
    image: "https://via.placeholder.com/300x300?text=Action+Camera",
  },
  {
    id: 9,
    name: "Wireless Mouse",
    brand: "Brand I",
    price: 4999,
    discountPrice: 4499,
    image: "https://via.placeholder.com/300x300?text=Wireless+Mouse",
  },
  {
    id: 10,
    name: "Smart Home Hub",
    brand: "Brand J",
    price: 9999,
    discountPrice: 8999,
    image: "https://via.placeholder.com/300x300?text=Smart+Home+Hub",
  },
];

export default electronicsProducts;