const groceryProducts = [
    {
      id: 1,
      name: "Organic Apples",
      brand: "Brand A",
      price: 3.99,
      image: "https://example.com/images/organic-apples.jpg",
      description: "Fresh organic apples, perfect for snacking.",
      specifications: {
        weight: "1 lb",
        origin: "USA",
        storageInstructions: "Refrigerate for freshness.",
      },
    },
    {
      id: 2,
      name: "Whole Wheat Bread",
      brand: "Brand B",
      price: 2.49,
      image: "https://example.com/images/whole-wheat-bread.jpg",
      description: "Nutritious whole wheat bread for sandwiches.",
      specifications: {
        weight: "16 oz",
        ingredients: "Whole wheat flour, water, yeast, salt.",
        storageInstructions: "Store in a cool, dry place.",
      },
    },
    {
      id: 3,
      name: "Almond Milk",
      brand: "Brand C",
      price: 2.99,
      image: "https://example.com/images/almond-milk.jpg",
      description: "Creamy almond milk, perfect for smoothies.",
      specifications: {
        volume: "32 fl oz",
        ingredients: "Almonds, water, salt.",
        storageInstructions: "Refrigerate after opening.",
      },
    },
    {
      id: 4,
      name: "Brown Rice",
      brand: "Brand D",
      price: 1.99,
      image: "https://example.com/images/brown-rice.jpg",
      description: "Healthy brown rice, a great side dish.",
      specifications: {
        weight: "2 lb",
        cookingInstructions: "Cook in boiling water for 45 minutes.",
        storageInstructions: "Store in a cool, dry place.",
      },
    },
    {
      id: 5,
      name: "Organic Spinach",
      brand: "Brand E",
      price: 2.49,
      image: "https://example.com/images/organic-spinach.jpg",
      description: "Fresh organic spinach, great for salads.",
      specifications: {
        weight: "5 oz",
        origin: "USA",
        storageInstructions: "Refrigerate for freshness.",
      },
    },
    {
      id: 6,
      name: "Free-Range Eggs",
      brand: "Brand F",
      price: 3.99,
      image: "https://example.com/images/free-range-eggs.jpg",
      description: "Fresh free-range eggs, rich in flavor.",
      specifications: {
        count: "12 eggs",
        origin: "USA",
        storageInstructions: "Refrigerate.",
      },
    },
    {
      id: 7,
      name: "Greek Yogurt",
      brand: "Brand G",
      price: 1.49,
      image: "https://example.com/images/greek-yogurt.jpg",
      description: "Creamy Greek yogurt, perfect for breakfast.",
      specifications: {
        volume: "5.3 oz",
        ingredients: "Milk, live cultures.",
        storageInstructions: "Refrigerate.",
      },
    },
    {
      id: 8,
      name: "Olive Oil",
      brand: "Brand H",
      price: 6.99,
      image: "https://example.com/images/olive-oil.jpg",
      description: "Extra virgin olive oil, ideal for cooking.",
      specifications: {
        volume: "16.9 fl oz",
        ingredients: "100% pure olive oil.",
        storageInstructions: "Store in a cool, dark place.",
      },
    },
    {
      id: 9,
      name: "Granola Bars",
      brand: "Brand I",
      price: 4.99,
      image: "https://example.com/images/granola-bars.jpg",
      description: "Healthy granola bars, perfect for on-the-go.",
      specifications: {
        count: "6 bars",
        ingredients: "Oats, honey, nuts.",
        storageInstructions: "Store in a cool, dry place.",
      },
    },
    {
      id: 10,
      name: "Frozen Mixed Vegetables",
      brand: "Brand J",
      price: 2.99,
      image: "https://example.com/images/frozen-mixed-vegetables.jpg",
      description: "Convenient frozen mixed vegetables for quick meals.",
      specifications: {
        weight: "16 oz",
        ingredients: "Carrots, peas, corn, green beans.",
        storageInstructions: "Keep frozen.",
      },
    },
  ];
  
export default groceryProducts;